{"name": "test_case_04[8]", "status": "failed", "statusDetails": {"message": "AssertionError: 偶数失败，奇数通过\nassert (8 % 2) != 0", "trace": "test\\case\\test_case_01.py:25: in test_case_04\n    assert data % 2 != 0, \"偶数失败，奇数通过\"\nE   AssertionError: 偶数失败，奇数通过\nE   assert (8 % 2) != 0"}, "description": "测试函数04", "attachments": [{"name": "log", "source": "5152205f-604c-4d6f-b225-322c12c83689-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "1553302d-4ab7-4446-9881-41b099b633c9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "8"}], "start": 1744527907746, "stop": 1744527907746, "uuid": "6b19e533-abc8-4dbb-b958-4673fae1a379", "historyId": "6cce62c627f92451843c2a69471460a5", "testCaseId": "c5e9abd4a563eaf91f172dfec7fabf2c", "fullName": "test.case.test_case_01#test_case_04", "labels": [{"name": "parentSuite", "value": "test.case"}, {"name": "suite", "value": "test_case_01"}, {"name": "host", "value": "AlansPc"}, {"name": "thread", "value": "26124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.case.test_case_01"}]}