{"name": "test_case_04[8]", "status": "failed", "statusDetails": {"message": "AssertionError: 偶数失败，奇数通过\nassert (8 % 2) != 0", "trace": "test\\case\\test_case_01.py:25: in test_case_04\n    assert data % 2 != 0, \"偶数失败，奇数通过\"\nE   AssertionError: 偶数失败，奇数通过\nE   assert (8 % 2) != 0"}, "description": "测试函数04", "attachments": [{"name": "log", "source": "a6639c1c-79a9-4656-9a7a-1b9bf42c20a3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d809ebd8-9adb-42b7-95b0-f4dee122fed5-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "8"}], "start": 1744526030582, "stop": 1744526030583, "uuid": "b86af86e-365b-4e91-a5d8-a030715b6228", "historyId": "6cce62c627f92451843c2a69471460a5", "testCaseId": "c5e9abd4a563eaf91f172dfec7fabf2c", "fullName": "test.case.test_case_01#test_case_04", "labels": [{"name": "parentSuite", "value": "test.case"}, {"name": "suite", "value": "test_case_01"}, {"name": "host", "value": "AlansPc"}, {"name": "thread", "value": "20620-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.case.test_case_01"}]}