{"name": "test_case_04[8]", "status": "failed", "statusDetails": {"message": "AssertionError: 偶数失败，奇数通过\nassert (8 % 2) != 0", "trace": "test\\case\\test_case_01.py:25: in test_case_04\n    assert data % 2 != 0, \"偶数失败，奇数通过\"\nE   AssertionError: 偶数失败，奇数通过\nE   assert (8 % 2) != 0"}, "description": "测试函数04", "attachments": [{"name": "log", "source": "cf89b3f2-060a-4723-a8f7-f4218ce65895-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "b4645542-f8af-45b7-b115-c65cff074549-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "8"}], "start": 1744526205402, "stop": 1744526205402, "uuid": "fa209801-f13e-4d31-b739-4e65e3ff4cc2", "historyId": "6cce62c627f92451843c2a69471460a5", "testCaseId": "c5e9abd4a563eaf91f172dfec7fabf2c", "fullName": "test.case.test_case_01#test_case_04", "labels": [{"name": "parentSuite", "value": "test.case"}, {"name": "suite", "value": "test_case_01"}, {"name": "host", "value": "AlansPc"}, {"name": "thread", "value": "25268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.case.test_case_01"}]}